/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.velomarker.openapi.api;

import eu.cokeman.velomarker.openapi.model.DemTileResponseDto;
import eu.cokeman.velomarker.openapi.model.DemTileTaskResponseDto;
import eu.cokeman.velomarker.openapi.model.DownloadDemTileRequestDto;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.22.0")
@Validated
@Controller
@Tag(name = "ElevationTiles", description = "the ElevationTiles API")
public interface ElevationTilesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DELETE_DEM_TILE = "/admin/elevation/tiles/{name}";
    /**
     * DELETE /admin/elevation/tiles/{name} : Delete an installed DEM tile (.tif)
     *
     * @param name Tile name without .tif (e.g. \&quot;N50E020\&quot;) (required)
     * @return Deleted (status code 204)
     */
    @Operation(
        operationId = "deleteDemTile",
        summary = "Delete an installed DEM tile (.tif)",
        tags = { "ElevationTiles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ElevationTilesApi.PATH_DELETE_DEM_TILE
    )
    default ResponseEntity<Void> deleteDemTile(
        @Parameter(name = "name", description = "Tile name without .tif (e.g. \"N50E020\")", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_DEM_TILE = "/admin/elevation/tiles/download";
    /**
     * POST /admin/elevation/tiles/download : Start async download of a Copernicus DEM tile
     *
     * @param downloadDemTileRequestDto  (required)
     * @return Task accepted (status code 202)
     */
    @Operation(
        operationId = "downloadDemTile",
        summary = "Start async download of a Copernicus DEM tile",
        tags = { "ElevationTiles" },
        responses = {
            @ApiResponse(responseCode = "202", description = "Task accepted", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DemTileTaskResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ElevationTilesApi.PATH_DOWNLOAD_DEM_TILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<DemTileTaskResponseDto> downloadDemTile(
        @Parameter(name = "DownloadDemTileRequestDto", description = "", required = true) @Valid @RequestBody DownloadDemTileRequestDto downloadDemTileRequestDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"taskId\" : \"taskId\", \"tileName\" : \"tileName\", \"status\" : \"QUEUED\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_DEM_TILES = "/admin/elevation/tiles";
    /**
     * GET /admin/elevation/tiles : List installed + available Copernicus DEM tiles (EU bbox by default)
     *
     * @param includeWorld If true, return all globe tiles. Default false &#x3D; EU only. (optional, default to false)
     * @return Catalog of DEM tiles + installed flags (status code 200)
     */
    @Operation(
        operationId = "listDemTiles",
        summary = "List installed + available Copernicus DEM tiles (EU bbox by default)",
        tags = { "ElevationTiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Catalog of DEM tiles + installed flags", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = DemTileResponseDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ElevationTilesApi.PATH_LIST_DEM_TILES,
        produces = { "application/json" }
    )
    default ResponseEntity<List<DemTileResponseDto>> listDemTiles(
        @Parameter(name = "includeWorld", description = "If true, return all globe tiles. Default false = EU only.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "includeWorld", required = false, defaultValue = "false") Boolean includeWorld
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"installed\" : true, \"outdated\" : true, \"latStart\" : 6, \"installedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"N50E020\", \"lonStart\" : 0, \"installedSizeBytes\" : 5, \"remoteSizeBytes\" : 1 }, { \"installed\" : true, \"outdated\" : true, \"latStart\" : 6, \"installedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"N50E020\", \"lonStart\" : 0, \"installedSizeBytes\" : 5, \"remoteSizeBytes\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
