/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.velomarker.openapi.api;

import eu.cokeman.velomarker.openapi.model.ManualSessionResponseDto;
import eu.cokeman.velomarker.openapi.model.ManualSessionUpsertRequestDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.22.0")
@Validated
@Controller
@Tag(name = "Manual", description = "the Manual API")
public interface ManualApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DELETE_MANUAL_SESSION = "/manual/session";
    /**
     * DELETE /manual/session : Delete the user&#39;s last manual route (explicit clear)
     *
     * @return Deleted (status code 204)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "deleteManualSession",
        summary = "Delete the user's last manual route (explicit clear)",
        tags = { "Manual" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ManualApi.PATH_DELETE_MANUAL_SESSION
    )
    default ResponseEntity<Void> deleteManualSession(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_MANUAL_SESSION = "/manual/session";
    /**
     * GET /manual/session : Get the user&#39;s last manually drawn route (one per user)
     *
     * @return Last manual route for authenticated user (status code 200)
     *         or No manual route saved yet (status code 204)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "getManualSession",
        summary = "Get the user's last manually drawn route (one per user)",
        tags = { "Manual" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Last manual route for authenticated user", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ManualSessionResponseDto.class))
            }),
            @ApiResponse(responseCode = "204", description = "No manual route saved yet"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ManualApi.PATH_GET_MANUAL_SESSION,
        produces = { "application/json" }
    )
    default ResponseEntity<ManualSessionResponseDto> getManualSession(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"geometryEncoded\" : \"geometryEncoded\", \"stats\" : { \"roadMeters\" : { \"key\" : 5 }, \"totalMeters\" : 1, \"surfaceSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ], \"roadSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ], \"surfaceMeters\" : { \"key\" : 5 }, \"smoothnessMeters\" : { \"key\" : 2 }, \"smoothnessSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ] }, \"profile\" : \"profile\", \"elevationLoss\" : 5, \"editedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"distanceKm\" : 1.4658129805029452, \"elevationGain\" : 5, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"waypoints\" : [ { \"lng\" : 0.8008281904610115, \"name\" : \"name\", \"lat\" : 6.027456183070403 }, { \"lng\" : 0.8008281904610115, \"name\" : \"name\", \"lat\" : 6.027456183070403 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPSERT_MANUAL_SESSION = "/manual/session";
    /**
     * PUT /manual/session : Upsert the user&#39;s last manual route (front saves only when finishing planning)
     *
     * @param manualSessionUpsertRequestDto  (required)
     * @return Saved (status code 200)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "upsertManualSession",
        summary = "Upsert the user's last manual route (front saves only when finishing planning)",
        tags = { "Manual" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Saved", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ManualSessionResponseDto.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ManualApi.PATH_UPSERT_MANUAL_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ManualSessionResponseDto> upsertManualSession(
        @Parameter(name = "ManualSessionUpsertRequestDto", description = "", required = true) @Valid @RequestBody ManualSessionUpsertRequestDto manualSessionUpsertRequestDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"geometryEncoded\" : \"geometryEncoded\", \"stats\" : { \"roadMeters\" : { \"key\" : 5 }, \"totalMeters\" : 1, \"surfaceSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ], \"roadSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ], \"surfaceMeters\" : { \"key\" : 5 }, \"smoothnessMeters\" : { \"key\" : 2 }, \"smoothnessSpans\" : [ { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 }, { \"code\" : \"code\", \"endIdx\" : 9, \"startIdx\" : 7 } ] }, \"profile\" : \"profile\", \"elevationLoss\" : 5, \"editedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"distanceKm\" : 1.4658129805029452, \"elevationGain\" : 5, \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"waypoints\" : [ { \"lng\" : 0.8008281904610115, \"name\" : \"name\", \"lat\" : 6.027456183070403 }, { \"lng\" : 0.8008281904610115, \"name\" : \"name\", \"lat\" : 6.027456183070403 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
