/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.velomarker.openapi.api;

import eu.cokeman.velomarker.openapi.model.ProfileContentDto;
import eu.cokeman.velomarker.openapi.model.ProfileSummaryDto;
import eu.cokeman.velomarker.openapi.model.SaveProfileRequestDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.22.0")
@Validated
@Controller
@Tag(name = "Profiles", description = "the Profiles API")
public interface ProfilesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DELETE_PROFILE = "/admin/route/profiles/{name}";
    /**
     * DELETE /admin/route/profiles/{name} : Delete a profile
     *
     * @param name  (required)
     * @return Deleted (status code 204)
     */
    @Operation(
        operationId = "deleteProfile",
        summary = "Delete a profile",
        tags = { "Profiles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ProfilesApi.PATH_DELETE_PROFILE
    )
    default ResponseEntity<Void> deleteProfile(
        @Parameter(name = "name", description = "", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_PROFILE = "/admin/route/profiles/{name}";
    /**
     * GET /admin/route/profiles/{name} : Read profile content (plain text .brf)
     *
     * @param name Profile filename without .brf suffix (required)
     * @return Profile content (status code 200)
     */
    @Operation(
        operationId = "getProfile",
        summary = "Read profile content (plain text .brf)",
        tags = { "Profiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile content", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProfileContentDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProfilesApi.PATH_GET_PROFILE,
        produces = { "application/json" }
    )
    default ResponseEntity<ProfileContentDto> getProfile(
        @Parameter(name = "name", description = "Profile filename without .brf suffix", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"modifiedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"content\" : \"content\", \"sizeBytes\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_PROFILES = "/admin/route/profiles";
    /**
     * GET /admin/route/profiles : List BRouter profiles available on disk (filesystem)
     *
     * @return Profile names + metadata (status code 200)
     */
    @Operation(
        operationId = "listProfiles",
        summary = "List BRouter profiles available on disk (filesystem)",
        tags = { "Profiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile names + metadata", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProfileSummaryDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProfilesApi.PATH_LIST_PROFILES,
        produces = { "application/json" }
    )
    default ResponseEntity<List<ProfileSummaryDto>> listProfiles(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"modifiedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"sizeBytes\" : 0 }, { \"modifiedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"sizeBytes\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SAVE_PROFILE = "/admin/route/profiles/{name}";
    /**
     * PUT /admin/route/profiles/{name} : Save profile content (atomic write, no worker restart needed)
     *
     * @param name  (required)
     * @param saveProfileRequestDto  (required)
     * @return Saved (status code 204)
     */
    @Operation(
        operationId = "saveProfile",
        summary = "Save profile content (atomic write, no worker restart needed)",
        tags = { "Profiles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Saved")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProfilesApi.PATH_SAVE_PROFILE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> saveProfile(
        @Parameter(name = "name", description = "", required = true, in = ParameterIn.PATH) @PathVariable("name") String name,
        @Parameter(name = "SaveProfileRequestDto", description = "", required = true) @Valid @RequestBody SaveProfileRequestDto saveProfileRequestDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
