/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.velomarker.openapi.api;

import eu.cokeman.velomarker.openapi.model.CalculateRouteRequestDto;
import eu.cokeman.velomarker.openapi.model.CalculateRouteResponseDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.22.0")
@Validated
@Controller
@Tag(name = "Routing", description = "the Routing API")
public interface RoutingApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CALCULATE_ROUTE = "/route/calculate";
    /**
     * POST /route/calculate : Calculate route geometry via BRouter (2D, no elevation)
     * Proxies to brouter container with Semaphore guard. Returns 2D LineString plus distance. Elevation is **not** returned from brouter — use POST /route/elevation separately (Copernicus DEM source). 
     *
     * @param calculateRouteRequestDto  (required)
     * @return Route calculated (status code 200)
     *         or Bad request (invalid waypoints, unknown profile) (status code 400)
     *         or Unauthorized (status code 401)
     *         or Brouter workers saturated, retry later (status code 429)
     *         or Brouter upstream error (status code 502)
     */
    @Operation(
        operationId = "calculateRoute",
        summary = "Calculate route geometry via BRouter (2D, no elevation)",
        description = "Proxies to brouter container with Semaphore guard. Returns 2D LineString plus distance. Elevation is **not** returned from brouter — use POST /route/elevation separately (Copernicus DEM source). ",
        tags = { "Routing" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Route calculated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CalculateRouteResponseDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request (invalid waypoints, unknown profile)"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "429", description = "Brouter workers saturated, retry later"),
            @ApiResponse(responseCode = "502", description = "Brouter upstream error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RoutingApi.PATH_CALCULATE_ROUTE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CalculateRouteResponseDto> calculateRoute(
        @Parameter(name = "CalculateRouteRequestDto", description = "", required = true) @Valid @RequestBody CalculateRouteRequestDto calculateRouteRequestDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"distanceKm\" : 6.027456183070403, \"geometry\" : { \"coordinates\" : [ [ 0.8008281904610115, 0.8008281904610115, 0.8008281904610115 ], [ 0.8008281904610115, 0.8008281904610115, 0.8008281904610115 ] ], \"type\" : \"LineString\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
