/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.velomarker.openapi.api;

import eu.cokeman.velomarker.openapi.model.DownloadSegmentRequestDto;
import org.springframework.lang.Nullable;
import eu.cokeman.velomarker.openapi.model.SegmentResponseDto;
import eu.cokeman.velomarker.openapi.model.SegmentTaskResponseDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.22.0")
@Validated
@Controller
@Tag(name = "Segments", description = "the Segments API")
public interface SegmentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DELETE_SEGMENT = "/admin/route/segments/{name}";
    /**
     * DELETE /admin/route/segments/{name} : Delete an installed segment (.rd5)
     *
     * @param name Segment name without .rd5 (e.g. \&quot;E20_N50\&quot;) (required)
     * @return Deleted (workers will be rolling-restarted) (status code 204)
     */
    @Operation(
        operationId = "deleteSegment",
        summary = "Delete an installed segment (.rd5)",
        tags = { "Segments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted (workers will be rolling-restarted)")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SegmentsApi.PATH_DELETE_SEGMENT
    )
    default ResponseEntity<Void> deleteSegment(
        @Parameter(name = "name", description = "Segment name without .rd5 (e.g. \"E20_N50\")", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_SEGMENT = "/admin/route/segments/download";
    /**
     * POST /admin/route/segments/download : Start async download of a segment
     *
     * @param downloadSegmentRequestDto  (required)
     * @return Task accepted (status code 202)
     */
    @Operation(
        operationId = "downloadSegment",
        summary = "Start async download of a segment",
        tags = { "Segments" },
        responses = {
            @ApiResponse(responseCode = "202", description = "Task accepted", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SegmentTaskResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SegmentsApi.PATH_DOWNLOAD_SEGMENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<SegmentTaskResponseDto> downloadSegment(
        @Parameter(name = "DownloadSegmentRequestDto", description = "", required = true) @Valid @RequestBody DownloadSegmentRequestDto downloadSegmentRequestDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"taskId\" : \"taskId\", \"segmentName\" : \"segmentName\", \"status\" : \"QUEUED\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_SEGMENTS = "/admin/route/segments";
    /**
     * GET /admin/route/segments : List installed + available segments (filtered to Europe by default)
     *
     * @param includeWorld If true, return all globe segments. Default false &#x3D; Europe only. (optional, default to false)
     * @return Catalog of all known segments + flags which are installed (status code 200)
     */
    @Operation(
        operationId = "listSegments",
        summary = "List installed + available segments (filtered to Europe by default)",
        tags = { "Segments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Catalog of all known segments + flags which are installed", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SegmentResponseDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SegmentsApi.PATH_LIST_SEGMENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<SegmentResponseDto>> listSegments(
        @Parameter(name = "includeWorld", description = "If true, return all globe segments. Default false = Europe only.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "includeWorld", required = false, defaultValue = "false") Boolean includeWorld
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"installed\" : true, \"outdated\" : true, \"latStart\" : 50, \"installedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"E20_N50\", \"lonStart\" : 20, \"installedSizeBytes\" : 6, \"remoteSizeBytes\" : 0 }, { \"installed\" : true, \"outdated\" : true, \"latStart\" : 50, \"installedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"E20_N50\", \"lonStart\" : 20, \"installedSizeBytes\" : 6, \"remoteSizeBytes\" : 0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
